# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

BUNDLE_IDENTIFIER = ENV["BUNDLE_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]

default_platform(:ios)

# Remove the temporary keychain, if it exists
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def build_flutter()
  sh('flutter', 'clean')
  sh('flutter', 'build', 'ios', '--release', '--no-sound-null-safety', '--no-codesign')
end

# Ensure we have a fresh, empty temporary keychain
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0,
    lock_when_sleeps: false,
    require_create: true
  )
end

platform :ios do
  desc "Build IPA for Apple Store submition"
  lane :beta do
    ensure_temp_keychain(ENV['TEMP_KEYCHAIN_NAME'], ENV['TEMP_KEYCHAIN_PASSWORD'])

    match(
      type: "appstore",
      readonly: true,
      keychain_name: ENV['TEMP_KEYCHAIN_NAME'],
      keychain_password: ENV["TEMP_KEYCHAIN_PASSWORD"],
      git_url: ENV["IOS_CREDENTIAL_REPO"]
    )

    build_flutter()

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )

    delete_temp_keychain(ENV['TEMP_KEYCHAIN_NAME'])
  end

  desc "Upload ipa to Apple Store"
  lane :deploy do
    pilot( 
      api_key_path: ENV['APPLE_CONNECT_API_KEY_JSON'],
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      ipa: "./Runner.ipa"
    )
  end
end
